Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LoginBD.Models
{
    public class Cliente
    {
        public int ClienteId { get; set; } 
        public string Nombre { get; set; } 
        public string Telefono { get; set; } 
        public string Direccion { get; set; } 
        public string Email { get; set; } 
        public decimal Monto { get; set; }
    }
}

Controllers/ClientesController.cs
using LoginBD.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LoginBD.Controllers
{
    public class ClientesController : Controller
    {
        private static ClientesController Instance { get; set; }
        public static ClientesController Instancia
        {
            get
            {
                if (Instance == null)
                { Instance = new ClientesController(); }
                return Instance;
            }
        }

        public List<Cliente> GetClientesDeudores()
        {
            var clientes = new List<Cliente>();

            using (SqlConnection sqlConnection = new SqlConnection(Conexion.Conexion.getConexion()))
            {
                sqlConnection.Open();
                //Idestadopaquete 1 es pendiente de pago
                var query = "SELECT TOP 5 Clientes.Nombre, Clientes.Direccion, Clientes.Email, Clientes.Telefono, sum(Paquete.Precio) AS Deuda FROM Clientes" +
                    "\r\ninner join paquete ON Paquete.ClienteId =Clientes.ClienteId and Paquete.IdEstadoPaquete = 1" +
                    "\r\nGROUP BY Clientes.Nombre, Clientes.Direccion, Clientes.Email, Clientes.Telefono\r\n" +
                    "ORDER BY Deuda DESC\r\n";
                using (var command = new SqlCommand(query, sqlConnection))
                {
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            var cliente = new Cliente
                            {
                                //   ClienteId = reader.GetInt32(reader.GetOrdinal("ClienteId")),
                                Nombre = reader.GetString(reader.GetOrdinal("Nombre")),
                                Telefono = reader.IsDBNull(reader.GetOrdinal("Telefono")) ? null : reader.GetString(reader.GetOrdinal("Telefono")),
                                Direccion = reader.IsDBNull(reader.GetOrdinal("Direccion")) ? null : reader.GetString(reader.GetOrdinal("Direccion")),
                                Email = reader.GetString(reader.GetOrdinal("Email")),
                                Monto = reader.GetDecimal(reader.GetOrdinal("Deuda"))
                            };
                            clientes.Add(cliente);
                        }
                    }
                }
            }

            return clientes;
        }



        [HttpGet]
        public List<Cliente> GetClientes()
        {
            var clientes = new List<Cliente>();

            using (SqlConnection sqlConnection = new SqlConnection(Conexion.Conexion.getConexion()))
            {
                sqlConnection.Open();

                var query = "SELECT ClienteId, Nombre, Telefono, Direccion, Email FROM Clientes";
                using (var command = new SqlCommand(query, sqlConnection))
                {
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            var cliente = new Cliente
                            {
                                ClienteId = reader.GetInt32(reader.GetOrdinal("ClienteId")),
                                Nombre = reader.GetString(reader.GetOrdinal("Nombre")),
                                Telefono = reader.IsDBNull(reader.GetOrdinal("Telefono")) ? null : reader.GetString(reader.GetOrdinal("Telefono")),
                                Direccion = reader.IsDBNull(reader.GetOrdinal("Direccion")) ? null : reader.GetString(reader.GetOrdinal("Direccion")),
                                Email = reader.GetString(reader.GetOrdinal("Email"))
                            };
                            clientes.Add(cliente);
                        }
                    }
                }
            }

            return clientes; ;
        }


        public List<Pago> GetPagos()
        {
            var pagos = new List<Pago>();

            using (SqlConnection sqlConnection = new SqlConnection(Conexion.Conexion.getConexion()))
            {
                sqlConnection.Open();

                var query = "SELECT Idpago, Monto,Fechapago,Paquete.Descripcion, Clientes.Nombre from Pagos" +
                    "\r\ninner join Paquete on Paquete.PaqueteId = Pagos.IdPaquete\r\ninner join Clientes on Clientes.ClienteId = Paquete.ClienteId";

                using (var command = new SqlCommand(query, sqlConnection))
                {
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            var pago = new Pago
                            {
                                IdPago = reader.GetInt32(reader.GetOrdinal("IdPago")),
                                Monto = reader.GetDecimal(reader.GetOrdinal("Monto")),
                                FechaPago = reader.GetDateTime(reader.GetOrdinal("FechaPago")).ToString("dd/MM/yyyy"),
                                Paquete = reader.GetString(reader.GetOrdinal("Descripcion")),
                                Cliente = reader.GetString(reader.GetOrdinal("Nombre"))
                            };
                            pagos.Add(pago);
                        }
                    }
                }
            }

            return pagos;
        }


    }
}

Controllers/HomeController.cs
using LoginBD.Models;
using LoginBD.Permisos;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LoginBD.Controllers
{
    public class HomeController : Controller
    {
        [ValidarSeisonAtribute]

        public ActionResult Pagos()
        {
            ViewBag.Pagos = ClientesController.Instancia.GetPagos();
            return View();
        }

        public ActionResult Clientes()
        {
            ViewBag.Clientes = ClientesController.Instancia.GetClientes();
            ViewBag.Deudores = ClientesController.Instancia.GetClientesDeudores();
            return View();
        }

        public ActionResult Paquetes()
        {
            ViewBag.Paquetes = PaquetesController.Instancia.GetPaquetes();
            ViewBag.Destinos = PaquetesController.Instancia.GetDestinos();
            return View();       
        }

        public ActionResult Viajes()
        {
            Paquete paquete = TempData["Paquete"] as Paquete; 

            if (paquete != null)
            {
                ViewBag.Paquete = paquete;
            }
            else
            {
                ViewBag.Error = "Paquete no encontrado.";
            }
            var estadias = PaquetesController.Instancia.GetEstadias(paquete.PaqueteId);
            if (estadias != null)
            {
                ViewBag.Estadias = estadias;
            }
            else
            {
                ViewBag.Error = "estadia no encontrada.";
            }
            return View();
        }


        public ActionResult CerrarSesion()
        {
            Session["usuario"] = null;
            return RedirectToAction("Login", "Acceso");
        }
    }
}

Controllers/PaquetesController.cs
using LoginBD.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LoginBD.Controllers
{
    public class PaquetesController : Controller
    {
        private static PaquetesController Instance { get; set; }
        public static PaquetesController Instancia
        {
            get
            {
                if (Instance == null)
                { Instance = new PaquetesController(); }
                return Instance;
            }
        }
      

        public List<Paquete> GetPaquetes()
        {
            var paquetes = new List<Paquete>();

            using (SqlConnection sqlConnection = new SqlConnection(Conexion.Conexion.getConexion()))
            {
                sqlConnection.Open();

                var queryPaquetes = @"
                SELECT 
                 p.PaqueteId, 
                 p.Descripcion AS PaqueteDescripcion,
                 p.CantidadPasajeros,
                 p.ClienteId,
                 p.Precio,
                 p.IdEstadoPaquete,
                 e.Descripcion AS EstadoPaqueteDescripcion
                FROM Paquete p
                INNER JOIN EstadoPaquete e ON p.IdEstadoPaquete = e.IdEstadoPaquete";

                using (var command = new SqlCommand(queryPaquetes, sqlConnection))
                {
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            var paquete = new Paquete
                            {
                                PaqueteId = reader.GetInt32(reader.GetOrdinal("PaqueteId")),
                                Descripcion = reader.GetString(reader.GetOrdinal("PaqueteDescripcion")),
                                CantidadPasajeros = reader.GetInt32(reader.GetOrdinal("CantidadPasajeros")),
                                ClienteId = reader.GetInt32(reader.GetOrdinal("ClienteId")),
                                Precio = reader.GetDecimal(reader.GetOrdinal("Precio")),
                                DescripcionEstado = reader.GetString(reader.GetOrdinal("EstadoPaqueteDescripcion")) // Agregar la descripción del estado
                            };
                            paquetes.Add(paquete);
                        }
                    }
                }

                // Obtener la información de los clientes
                var clienteIds = paquetes.Select(p => p.ClienteId).Distinct().ToList();
                if (clienteIds.Any())
                {
                    var queryClientes = "SELECT * FROM Clientes WHERE ClienteId IN (" + string.Join(",", clienteIds) + ")";
                    var clientes = new Dictionary<int, Cliente>();

                    using (var command = new SqlCommand(queryClientes, sqlConnection))
                    {
                        using (var reader = command.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                var cliente = new Cliente
                                {
                                    ClienteId = reader.GetInt32(reader.GetOrdinal("ClienteId")),
                                    Nombre = reader.GetString(reader.GetOrdinal("Nombre")),
                                    Telefono = reader.IsDBNull(reader.GetOrdinal("Telefono")) ? null : reader.GetString(reader.GetOrdinal("Telefono")),
                                    Direccion = reader.IsDBNull(reader.GetOrdinal("Direccion")) ? null : reader.GetString(reader.GetOrdinal("Direccion")),
                                    Email = reader.GetString(reader.GetOrdinal("Email"))
                                };
                                clientes[cliente.ClienteId] = cliente;
                            }
                        }
                    }

                    // Asociar cada cliente a su respectivo paquete
                    foreach (var paquete in paquetes)
                    {
                        if (clientes.TryGetValue(paquete.ClienteId, out var cliente))
                        {
                            paquete.Cliente = cliente.Nombre;
                        }
                    }
                }
            }
            return paquetes;
        }



        public List<Destino> GetDestinos()
        {
            var destinos = new List<Destino>();

            using (SqlConnection sqlConnection = new SqlConnection(Conexion.Conexion.getConexion()))
            {
                sqlConnection.Open();

                var query = @"
                SELECT TOP 3
                    d.IdDestino,
                    d.Pais,
                    d.Provincia,
                    d.Descripcion,
                    COUNT(e.IdEstadia) AS NumeroDeVisitas
                FROM
                    Destinos d
                    INNER JOIN Hoteles h ON d.IdDestino = h.IdDestino
                    INNER JOIN Estadias e ON h.IdHotel = e.IdHotel
                GROUP BY
                    d.IdDestino,
                    d.Pais,
                    d.Provincia,
                    d.Descripcion
                ORDER BY
                    NumeroDeVisitas DESC;
            ";

                using (var command = new SqlCommand(query, sqlConnection))
                {
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            var destino = new Destino
                            {
                                IdDestino = reader.GetInt32(reader.GetOrdinal("IdDestino")),
                                Pais = reader.GetString(reader.GetOrdinal("Pais")),
                                Provincia = reader.GetString(reader.GetOrdinal("Provincia")),
                                Descripcion = reader.GetString(reader.GetOrdinal("Descripcion")),
                                NumeroVisitas = reader.GetInt32(reader.GetOrdinal("NumeroDeVisitas"))
                            };
                            destinos.Add(destino);
                        }
                    }
                }
            }

            return destinos;
        }


        public List<Estadia> GetEstadias(int PaqueteId)
        {
            List<Estadia> estadias = new List<Estadia>();

            using (SqlConnection sqlConnection = new SqlConnection(Conexion.Conexion.getConexion()))
            {
                sqlConnection.Open();
                string query = @"
            SELECT 
                Estadias.IdEstadia,
                Estadias.FechaLlegada, 
                Estadias.FechaSalida, 
                Hoteles.Nombre AS Hotel, 
                Destinos.Pais AS Ubicacion
            FROM Estadias
            INNER JOIN Hoteles ON Estadias.IdHotel = Hoteles.IdHotel
            INNER JOIN Destinos ON Hoteles.IdDestino = Destinos.IdDestino
            WHERE Estadias.IdPaquete = @PaqueteId";

                using (SqlCommand command = new SqlCommand(query, sqlConnection))
                {
                    command.Parameters.AddWithValue("@PaqueteId", PaqueteId);

                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            estadias.Add(new Estadia
                            {
                                IdEstadia = reader.GetInt32(reader.GetOrdinal("IdEstadia")),
                                FechaLlegada = reader.GetDateTime(reader.GetOrdinal("FechaLlegada")),
                                FechaSalida = reader.GetDateTime(reader.GetOrdinal("FechaSalida")),
                                Ubicacion = reader.GetString(reader.GetOrdinal("Ubicacion")),
                                Hotel = reader.GetString(reader.GetOrdinal("Hotel"))
                            });
                        }
                    }
                }
            }

            return estadias;
        }

        public ActionResult GetPaqueteById(int? paqueteId)
        {
            if (paqueteId.HasValue)
            {
                Paquete paquete = null;

                using (SqlConnection sqlConnection = new SqlConnection(Conexion.Conexion.getConexion()))
                {
                    sqlConnection.Open();
                    var queryPaquetes = @"
            SELECT 
                p.PaqueteId, 
                p.Descripcion AS PaqueteDescripcion,
                p.CantidadPasajeros,
                p.ClienteId,
                p.Precio,
                p.IdEstadoPaquete,
                e.Descripcion AS EstadoPaqueteDescripcion
            FROM Paquete p
            INNER JOIN EstadoPaquete e ON p.IdEstadoPaquete = e.IdEstadoPaquete 
            WHERE PaqueteId = @paqueteId";


                    using (var command = new SqlCommand(queryPaquetes, sqlConnection))
                    {

                        command.Parameters.AddWithValue("@paqueteId", paqueteId.Value);

                        using (var reader = command.ExecuteReader())
                        {
                            if (reader.Read())
                            {
                                paquete = new Paquete
                                {
                                    PaqueteId = reader.GetInt32(reader.GetOrdinal("PaqueteId")),
                                    Descripcion = reader.GetString(reader.GetOrdinal("PaqueteDescripcion")),
                                    CantidadPasajeros = reader.GetInt32(reader.GetOrdinal("CantidadPasajeros")),
                                    ClienteId = reader.GetInt32(reader.GetOrdinal("ClienteId")),
                                    Precio = reader.GetDecimal(reader.GetOrdinal("Precio")),

Views/Home/Clientes.cshtml
@using LoginBD.Models
@{
 //   ViewBag.Title = "Lista de Paquetes y Destinos Más Visitados";
    var clientes = ViewBag.Clientes as List<Cliente>;
    var deudores = ViewBag.Deudores as List<Cliente>;
}
<html>
<head>
    <title>Lista de Clientes</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h4>Lista de Clientes</h4>
                <div class="table-responsive">
                    <table id="clientesTable" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nombre</th>
                                <th>Teléfono</th>
                                <th>Dirección</th>
                                <th>Email</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (clientes != null && clientes.Any())
                            {
                                foreach (var c in clientes)
                                {
                                    <tr>
                                        <td>@c.ClienteId</td>
                                        <td>@c.Nombre</td>
                                        <td>@c.Telefono</td>
                                        <td>@c.Direccion</td>
                                        <td>@c.Email</td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="5">No se encontraron clientes.</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>


        <div class="row table-container">
            <div class="col-md-12">
                <h4>Clientes con mas deudas</h4>
                <div class="table-responsive">
                    <table id="DeudasTable" class="table table-bordered table-striped">
                        <thead>
                            <tr>

                                <th>Nombre</th>
                                <th>Teléfono</th>
                                <th>Dirección</th>
                                <th>Email</th>
                                <th>Monto</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (deudores != null && deudores.Any())
                            {
                                foreach (var d in deudores)
                                {
                                    <tr>
                                        <td>@d.Nombre</td>
                                        <td>@d.Telefono</td>
                                        <td>@d.Direccion</td>
                                        <td>@d.Email</td>
                                        <td>@d.Monto</td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="5">No se encontraron deudores.</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Views/Home/Paquetes.cshtml
@using LoginBD.Models
@{
    ViewBag.Title = "Lista de Paquetes y Destinos Más Visitados";
    var paquetes = ViewBag.Paquetes as List<Paquete>;
    var destinos = ViewBag.Destinos as List<Destino>;
}

<head>
    <style>
       
        span.red {
            background-color: red;
            border-radius: 50%;
            width: 16px;
            height: 16px;
            display: inline-block;
        }

        span.green {
            background-color: green;
            border-radius: 50%;
            width: 16px;
            height: 16px;
            display: inline-block;
        }

        span.black {
            background-color: black;
            border-radius: 50%;
            width: 16px;
            height: 16px;
            display: inline-block;
        }

        span.grey {
            background-color: grey;
            border-radius: 50%;
            width: 16px;
            height: 16px;
            display: inline-block;
        }
    </style>
</head>
<html>
<body>
    <div class="container">

        <div class="row">
            <div class="col-md-12">
                <h4>Lista de Paquetes</h4>
                <div class="table-responsive">
                    <table id="paquetesTable" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Descripción</th>
                                <th>Cantidad de Pasajeros</th>
                                <th>Cliente</th>
                                <th>Precio</th>
                                <th>Estado</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (paquetes != null && paquetes.Any())
                            {
                                foreach (var paquete in paquetes)
                                {
                                    string estadoCirculo = "";
                                    switch (paquete.DescripcionEstado)
                                    {
                                        case "Pagado":
                                            estadoCirculo = "<span class='green'></span>";
                                            break;
                                        case "Pendiente de Pago":
                                            estadoCirculo = "<span class='red'></span>";
                                            break;
                                        case "Cancelado":
                                            estadoCirculo = "<span class='grey'></span>";
                                            break;
                                        default:
                                            estadoCirculo = "<span class='grey'></span>";
                                            break;
                                    }

                                    <tr>
                                        <td>@paquete.PaqueteId</td>
                                        <td>@paquete.Descripcion</td>
                                        <td>@paquete.CantidadPasajeros</td>
                                        <td>@paquete.Cliente?.Nombre</td>
                                        <td>@paquete.Precio</td>
                                        <td>
                                            @Html.Raw(estadoCirculo) @paquete.DescripcionEstado
                                        </td>
                                        <td>
                                            <a href="@Url.Action("GetPaqueteById", "Paquetes", new { paqueteId = paquete.PaqueteId })" class="btn btn-sm btn-success">
                                                <span class="glyphicon glyphicon-arrow-right"></span> Ver detalles
                                            </a>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="7">No se encontraron paquetes.</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
  
        <div class="row table-container">
            <div class="col-md-12">
                <h4>Destinos Más Visitados</h4>
                <div class="table-responsive">
                    <table id="destinosTable" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>ID Destino</th>
                                <th>País</th>
                                <th>Provincia</th>
                                <th>Descripción</th>
                                <th>Número de Visitas</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (destinos != null && destinos.Any())
                            {
                                foreach (var destino in destinos)
                                {
                                    <tr>
                                        <td>@destino.IdDestino</td>
                                        <td>@destino.Pais</td>
                                        <td>@destino.Provincia</td>
                                        <td>@destino.Descripcion</td>
                                        <td>@destino.NumeroVisitas</td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="5">No se encontraron destinos.</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Views/Home/Viajes.cshtml
@{
    var paquete = ViewBag.Paquete as LoginBD.Models.Paquete;
    var Estadias = ViewBag.Estadias as List<LoginBD.Models.Estadia>;
    var error = ViewBag.Error;
}

<div class="container">
    <h2>Detalles del Viaje</h2>

    @if (paquete != null)
    {
        <div>
            <p><strong>ID del Paquete:</strong> @paquete.PaqueteId</p>
            <p><strong>Descripción:</strong> @paquete.Descripcion</p>
            <p><strong>Cantidad de Pasajeros:</strong> @paquete.CantidadPasajeros</p>
            <p><strong>Cliente ID:</strong> @paquete.ClienteId</p>
            <p><strong>Precio:</strong> $@paquete.Precio</p>
            <p><strong>Estado del paquete:</strong> @paquete.DescripcionEstado</p>
        </div>
    }
    else if (error != null)
    {
        <div class="alert alert-danger">
            @error
        </div>
    }

    <div class="container">
        <h4>Lista de Estadías</h4>
        <div class="table-responsive">
            <table id="estadiasTable" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>ID Estadía</th>
                        <th>Fecha de Llegada</th>
                        <th>Fecha de Salida</th>
                        <th>Ubicación</th>
                        <th>Hotel</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Estadias != null && Estadias.Any())
                    {
                        foreach (var e in Estadias)
                        {
                            <tr>
                                <td>@e.IdEstadia</td>
                                <td>@e.FechaLlegada</td>
                                <td>@e.FechaSalida</td>
                                <td>@e.Ubicacion</td>
                                <td>@e.Hotel</td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="5">No se encontraron estadías.</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Views/Home/pagos.cshtml
@using LoginBD.Models
@{
    var pagos = ViewBag.Pagos as List<Pago>;
}
<html>
<head>
    <title>Pagos</title> 
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h4>Lista de Pagos</h4>
                <div class="table-responsive">
                    <table id="pagosTable" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Monto</th>
                                <th>Fecha de pago</th>
                                <th>Paquete</th>
                                <th>Cliente</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (pagos != null && pagos.Any())
                            {
                                foreach (var pago in pagos)
                                {
                                    <tr>
                                        <td>@pago.Monto</td>
                                        <td>@pago.FechaPago</td>
                                        <td>@pago.Paquete</td>
                                        <td>@pago.Cliente</td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="5">No se encontraron pagos.</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</body>
</html>